version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    reviewers:
      - "oeffis/core-team"
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
    reviewers:
      - "oeffis/core-team"
