name: Backend CI

on: 
  push:
    branches:
      - main
    paths: 
      - backend/**
      - .github/workflows/backend_ci.yml

env:
  GITHUB_REGISTRY: ghcr.io
  GITHUB_IMAGE_NAME: oeffis/oeffis/backend
  DOCKER_HUB_IMAGE_NAME: oeffis/backend

jobs:
    backend_ci:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Install Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18.x
        - name: Install Dependencies
          working-directory: backend
          run: |
            npm ci
        - name: Lint
          working-directory: backend
          run: |
            npm run lint -- --max-warnings 0 --no-fix
        - name: Test
          working-directory: backend
          run: |
            npm run test
        - name: Build
          working-directory: backend
          run: |
            npm run build

    container_build:
      name: Build Container
      needs: backend_ci
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

    container_github:
      name: Deploy Container to GitHub Container Registry
      needs: container_build
      if: (github.event_name == 'push' && contains(github.ref, 'refs/tags/'))
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - name: Log in to the Container registry
          uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
          with:
            registry: ${{ env.GITHUB_REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build
          uses: docker/build-push-action@v4
          with:
            context: backend
            platforms: linux/amd64,linux/arm64
            push: true
            tags: ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_IMAGE_NAME }}:latest
  
    container_dockerhub:
      name: Deploy Container to DockerHub
      needs: container_build
      if: (github.event_name == 'push' && contains(github.ref, 'refs/tags/'))
      runs-on: ubuntu-latest
      steps:
        - name: Log in to the Container registry
          uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
          with:
            username: ${{ secrets.DOCKER_HUB_USER }}
            password: ${{ secrets.DOCKER_HUB_PASS }}
        - name: Build
          uses: docker/build-push-action@v4
          with:
            context: backend
            platforms: linux/amd64,linux/arm64
            push: true
            tags: ${{ env.DOCKER_HUB_IMAGE_NAME }}:latest
