name: Container CI

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - .github/workflows/container_ci.yml
      - backend/Dockerfile
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: oeffis/${{ github.repository }}/backend

jobs:
  container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
