name: Frontend CI

on:
  push:
  merge_group:

env:
  GITHUB_REGISTRY: ghcr.io
  GITHUB_IMAGE_NAME: oeffis/oeffis/frontend
  DOCKER_HUB_IMAGE_NAME: docker.io/oeffis/frontend

jobs:
    frontend_ci:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Install Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18.x

        - name: Install Dependencies
          working-directory: frontend
          run: |
            npm ci

        - name: Lint
          working-directory: frontend
          run: |
            npm run lint -- --max-warnings 0 --no-fix

        - name: Test
          working-directory: frontend
          run: |
            npm run test.unit -- run

        - name: Build
          working-directory: frontend
          run: |
            npm run build


    container:
      name: Build and Deploy Container
      needs: frontend_ci
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'
      permissions:
        contents: read
        packages: write
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Log in to the Container registry
          uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
          with:
            username: ${{ secrets.DOCKER_HUB_USER }}
            password: ${{ secrets.DOCKER_HUB_PASS }}

        - name: Log in to the Container registry
          uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
          with:
            registry: ${{ env.GITHUB_REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build
          uses: docker/build-push-action@v4
          with:
            context: backend
            platforms: linux/amd64,linux/arm64
            push: true
            tags: ${{ env.DOCKER_HUB_IMAGE_NAME }}:latest,${{ env.GITHUB_IMAGE_NAME }}:latest
